apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  namespace: external-dns
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
      - name: external-dns
        image: registry.k8s.io/external-dns/external-dns:v0.13.5
        args:
          - --source=ingress # ingress is also possible
          - --zone-id-filter=f1b4777ef623716324f9af14b408863a
          - --domain-filter=int.comboio.party # (optional) limit to only example.com domains; change to match the zone created above.
          - --provider=cloudflare
          - --cloudflare-dns-records-per-page=5000 # (optional) configure how many DNS records to fetch per request
        env:
        - name: CF_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: api
              key: CF_API_TOKEN