apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: api
  namespace: external-dns
spec:
  encryptedData:
    CF_API_EMAIL: AgB47Q6zAgzKxd0cx60LMgtKd86Dc841IIBicCxBAZO6pTNcKvTAXwYiB/i7emBFLgp7j+MzTWv7MT97yPrNvZbV0q+4sN9srYsa5XOykzyrykInxvQ9oJdz+II/5mavk7BbvoBC7iEaghwzwHpNypcUfDDiDsO6Bizshwr6Ght6B+O5gyf/0Hj6gONXcIULn0sLZdsXpDjwpwJlTLrVa+DNE7b7/6NRsYKeJqM4PHTjTgMJ3s3mKfpy3GDooPhHC10b7c4a0Ez8Jma3iQvshTWLDg3PoeL0P8CeSF6WdlzPcHFbQXBVrJVFTtw4vNfpQKZeLbOwLaKx0PUxk2JnI8t5zmAkr0X7ZclxF/2vCCwLYD3cvP5k3iQ5OOopv8sGeEHPX7CcnmpalKBH6UVWiaVyw6WK6wb4gMWD3q2FkH/upk1bnf3HPEy0unxucVK1LkwxjHQXxj2EHBFmaEf4QnQ1v5liMix3I+IcYTZ7YeVAypXG0teBqYXdQMZOM+LiWZQv50642gkr48BtE+YXtdN398LOXEn6XIPu95FZO2L8imRnisC3UaAeQ8m5PegFrkNxT/aS/GadxaEb8avgI6Kq2Mf4t1+7t9Kbi0vTJFLoaPJ7aHeC/a3NaaYAGYP/qVIDFU7JHjIkImgRmmZxnMS4zvDXzgyWg1bOSQVYQhtKw94gK/yI1VMfuyfbTGJE6LiAhy9qWd37w0dQmO7YLZfqgg==
    CF_API_KEY: AgCVXrKesISUBQ+uMUvk2y6Fs3vFOAxHOlRBAkf/nnPEFmD7o00gAr0KoHW/3o9rfzX+LiL0xCdWohO/Cq9nYDCWQ1VWT3Kou81CXy+7TGfDSaue0B9hDYBWg6ZzWbEF4uqaei7d/NMjy1BF6tzfWGuqPgrfYDx7pBHtn6eosd+ILMmwlXef6QWegTq//12ZGNXuS7u5gE3e6SFz64uO41X+lkPLr+sXovmajz4fJI+4OLtA12TH3XBAb2lbxQ4saWiZYBY58uM2vjm9EQnmFsV5Ns4YV1fn9oFbslRGmhzgjjOvnHwqf65DO/Hu8xXr8XqKlK5Ia5hVfaubIR8imNyiY/UujjhlJazvi8tM+5UdoZlwGjnaOb1rppFu99K/jPpECNxalpHOwbhUp8FmjKmHRds1qfOfiKZHKXz+ktvKT76N3nMSSqVQ/qBklNPpiV5JpZz9DHUtgM5VxGurcHMFAEd/Tsj45uxXZ7L4meQX6lbnGx9MAtZ+x7F5xnLarzQ4e2lJVoBIN1xQJyaV5hD3+QJhq2dpgsBMPqbF+0fAsZxKVB7BxtS4Yw/ifHRhsyrHxo1W2VuQsSZKwnkFqbdbAkH0nQoaKfFtPwdgeW52VUr9q2uA1gpoBm34sM9DbO+tl9niA/iItATZAl4j18xU3wT5Kuhh/1ETuWalyhh35Kgf8BtvowWLEJwHxaWbxgzSr4B+s8Oz7IuyayCFZXXEI0SjzlFclSHnjErnux/8DyBhFo7RXd8J
  template:
    metadata:
      creationTimestamp: null
      name: api
      namespace: external-dns
    type: Opaque

