apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applications
spec:
  generators:
    - git:
        repoURL: https://github.com/thiagoabdo/home-ansible.git
        revision: HEAD
        directories:
          - path: argocd-apps/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      destination:
        name: in-cluster
        namespace: '{{path.basename}}'
      project: default # TODO
      source:
        repoURL: https://github.com/thiagoabdo/home-ansible.git
        path: '{{path}}'
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 10
          backoff:
            duration: 1m
            factor: 2
            maxDuration: 16m
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true