apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: api
  namespace: cert-manager
spec:
  encryptedData:
    CF_API_TOKEN: AgBZDrR29RETjEAe2Ssgbud5YlTYmO6Mvq7wF47599IhrZzLzWLjPsVa664KDSA2isa8dbPfsNXSFuB6TcvRjjMkn91d+6XIheWoNFEeFllkyMLYI7eWYGBHYmppPWsMLVXBMBfE9FLRwuamZvTIyCrUorr+8o2MTqq2/QNILOdXhL1sXF5ArEQuSfj96CQboDupslOwVSzH59Pz4JdW9uwusxEGfJgl/TjHtWyJLRMZBbBWClfQKMrxYXkawXj86/+Qi/vvNV6WwanD7vS0ztXzsWF11bphUqGl9Xqs247g/vGDLGFDLYkezxk9JiMAALAxJpX7Ld6qyj9OItPDSvkl72QKuvbuq3t9DMzNG3EDGsoIPezXSCHlD1LBZggjqw8Ac15+8ZOYRoYG81ofh894um4WURCjcwrB6Z1hfoVLCUVvQ39+JgCu8pSWe6tCD3GQG3cIo/yxWFZZKhkZamQeD0WOiqhlhVCrZg+EbwYGId5Bvdg5BNpONSGrNqm4Q9dk86xpv+JuxFx94Kf/jXYuZsdJfniH5k6IoG9dXjYFeQ+cwSbtbuuYxN/OLs9XoOFim9U3akl/3gBB0acF4B1tFjqwvjCvaBg9lxIJNBW72VKfPKZldYNBFUHsJf9JVMnPcoKXoatITeFk+8xfIyDx4fSxZP0H4VkmckHHfYFMTtxawff+EvxkJrbZClaOB2HO4+d+B71SVxFQgxYq0ExbtUHllDgZNHkDDzZglKeBqn5gakpb9VJp
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: api
      namespace: cert-manager
    type: Opaque

