longhorn:
  helmPreUpgradeCheckerJob:
    enabled: false
  defaultSettings:
    nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
  persistence:
    # If you have three or more nodes for storage, use 3; otherwise use 2
    defaultClassReplicaCount: 1  # TODO run DR test to see if we actually need 3

  ingress:
    enabled: true
    ingressClassName: nginx-public
    host: longhorn.int.comboio.party
    tls: true
