apiVersion: v2
name: home-assistant
version: 0.0.0
dependencies:
  - name: home-assistant
    version: 13.4.2
    repository: https://k8s-at-home.com/charts/
  - name: mosquitto
    version: 4.8.2
    repository: https://k8s-at-home.com/charts/
  - name: zigbee2mqtt
    version: 9.4.2
    repository: https://k8s-at-home.com/charts/
  - name: esphome
    version: 8.4.2